name: angular_template_parser
homepage: https://github.com/dart-lang/angular_template_parser
description: Parse Angular Dart templates into ASTs
version: 0.1.0-dev

authors:
  - Matan Lurey <matanl@google.com>
  - Jonah Williams <jonahwilliams@google.com>

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  analyzer:
  charcode: ">=1.1.0 <2.0.0"
  collection: "^1.0.0"
  meta: "^1.0.4"
  string_scanner: "^1.0.0"
  quiver:

dev_dependencies:
  angular2:
  benchmark_harness:
  browser:
  codemirror:
  dart_style:
  test:
